// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package led_regs_pkg;

    localparam LED_REGS_DATA_WIDTH = 32;
    localparam LED_REGS_MIN_ADDR_WIDTH = 3;
    localparam LED_REGS_SIZE = 'h4;

    typedef struct {
        logic value;
    } led_regs__CONTROL__ENABLE__out_t;

    typedef struct {
        logic [3:0] value;
    } led_regs__CONTROL__BLINK_RATE__out_t;

    typedef struct {
        led_regs__CONTROL__ENABLE__out_t ENABLE;
        led_regs__CONTROL__BLINK_RATE__out_t BLINK_RATE;
    } led_regs__CONTROL__out_t;

    typedef struct {
        led_regs__CONTROL__out_t control_inst;
    } led_regs__out_t;
endpackage
