// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module led_regs (
        input wire clk,
        input wire rst,

        input wire s_cpuif_req,
        input wire s_cpuif_req_is_wr,
        input wire [2:0] s_cpuif_addr,
        input wire [31:0] s_cpuif_wr_data,
        input wire [31:0] s_cpuif_wr_biten,
        output wire s_cpuif_req_stall_wr,
        output wire s_cpuif_req_stall_rd,
        output wire s_cpuif_rd_ack,
        output wire s_cpuif_rd_err,
        output wire [31:0] s_cpuif_rd_data,
        output wire s_cpuif_wr_ack,
        output wire s_cpuif_wr_err,

        output led_regs_pkg::led_regs__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [2:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    assign cpuif_req = s_cpuif_req;
    assign cpuif_req_is_wr = s_cpuif_req_is_wr;
    assign cpuif_addr = s_cpuif_addr;
    assign cpuif_wr_data = s_cpuif_wr_data;
    assign cpuif_wr_biten = s_cpuif_wr_biten;
    assign s_cpuif_req_stall_wr = cpuif_req_stall_wr;
    assign s_cpuif_req_stall_rd = cpuif_req_stall_rd;
    assign s_cpuif_rd_ack = cpuif_rd_ack;
    assign s_cpuif_rd_err = cpuif_rd_err;
    assign s_cpuif_rd_data = cpuif_rd_data;
    assign s_cpuif_wr_ack = cpuif_wr_ack;
    assign s_cpuif_wr_err = cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic control_inst;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        decoded_reg_strb.control_inst = cpuif_req_masked & (cpuif_addr == 3'h0);
    end

    // Pass down signals to next stage
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } ENABLE;
            struct {
                logic [3:0] next;
                logic load_next;
            } BLINK_RATE;
        } control_inst;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } ENABLE;
            struct {
                logic [3:0] value;
            } BLINK_RATE;
        } control_inst;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: led_regs.control_inst.ENABLE
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control_inst.ENABLE.value;
        load_next_c = '0;
        if(decoded_reg_strb.control_inst && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control_inst.ENABLE.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.control_inst.ENABLE.next = next_c;
        field_combo.control_inst.ENABLE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control_inst.ENABLE.value <= 1'h0;
        end else begin
            if(field_combo.control_inst.ENABLE.load_next) begin
                field_storage.control_inst.ENABLE.value <= field_combo.control_inst.ENABLE.next;
            end
        end
    end
    assign hwif_out.control_inst.ENABLE.value = field_storage.control_inst.ENABLE.value;
    // Field: led_regs.control_inst.BLINK_RATE
    always_comb begin
        automatic logic [3:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.control_inst.BLINK_RATE.value;
        load_next_c = '0;
        if(decoded_reg_strb.control_inst && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.control_inst.BLINK_RATE.value & ~decoded_wr_biten[4:1]) | (decoded_wr_data[4:1] & decoded_wr_biten[4:1]);
            load_next_c = '1;
        end
        field_combo.control_inst.BLINK_RATE.next = next_c;
        field_combo.control_inst.BLINK_RATE.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(rst) begin
            field_storage.control_inst.BLINK_RATE.value <= 4'h2;
        end else begin
            if(field_combo.control_inst.BLINK_RATE.load_next) begin
                field_storage.control_inst.BLINK_RATE.value <= field_combo.control_inst.BLINK_RATE.next;
            end
        end
    end
    assign hwif_out.control_inst.BLINK_RATE.value = field_storage.control_inst.BLINK_RATE.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;

    // Assign readback values to a flattened array
    logic [31:0] readback_array[1];
    assign readback_array[0][0:0] = (decoded_reg_strb.control_inst && !decoded_req_is_wr) ? field_storage.control_inst.ENABLE.value : '0;
    assign readback_array[0][4:1] = (decoded_reg_strb.control_inst && !decoded_req_is_wr) ? field_storage.control_inst.BLINK_RATE.value : '0;
    assign readback_array[0][31:5] = '0;

    // Reduce the array
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
        readback_data_var = '0;
        for(int i=0; i<1; i++) readback_data_var |= readback_array[i];
        readback_data = readback_data_var;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
